version: '3'

services:
  geth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./ethereum-data:/root/.ethereum
    command: >
      --datadir /root/.ethereum
      --networkid 1337
      --mine
      --miner.threads 1
      --http
      --http.addr "0.0.0.0"
      --http.port 8545
      --http.corsdomain "*"
      --http.api "eth,net,web3,debug,txpool,personal"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port 8546
      --ws.origins "*"
      --ws.api "eth,net,web3,debug,txpool,personal"
      --rpc.allow-unprotected-txs
      --syncmode "full"
      --gcmode "archive"
      --txlookuplimit 0
      --allow-insecure-unlock
      --verbosity 3
    restart: unless-stopped
